### PR TITLE
Add Modifier modules and their examples

### PR DESCRIPTION
**Pull request by Razaekel**
Also added cubic interpolation for Curve's use

### CODE REVIEW

**Comment by brendanzab** [comment]
Super duper awesome work! So sorry for me avoiding my responsibilities in merging :(

I'm just onedering how many of these modules we could remove by simply having a higher-order module that took a function? Like `Abs` could be:

```
FnModule::new(f32::abs, perlin)
```

Or something...

Same goes for the modules added in #123.

**Comment by brendanzab** [comment]
Or maybe we could have a `Module::map` function. Like:

```rust
Perlin::new(0).map(f32::abs)
```

**Comment by Razaekel** [comment]
I don't have an issue with adding a specific Map module, but I'd rather not remove the existing modules. I'd like to keep them for composition (always return a NoiseModule object for chaining, and never specify whether it's f32 or f64) and understandability(Abs::new(perlin) is easier to read at a glance than FnModule::new(f32::abs, perlin)) reasons, as well as having individual modules for what are likely to be more commonly used operations.

**Comment by brendanzab** [comment]
If we had `impl NoiseModule` it would be much nicer (similar problem goes for iterators). I'll merge this anyway though.

**Comment by Razaekel** [comment]
impl Trait is still in progress, but yes, that would make some of these NoiseModules nicer/redundant.

**Pull request merged**
